version: "3"
services:
 krakend:
    image: devopsfaith/krakend
    ports:
      - 8080:8080
    volumes:
      - ./gateway:/etc/krakend

 grafana:
    image: grafana/grafana:9.1.2
    ports:
      - "4000:3000"
    volumes:
      - ./gateway/monitoring/grafana/datasources/all.yml:/etc/grafana/provisioning/datasources/all.yml
      - ./gateway/monitoring/grafana/dashboards/all.yml:/etc/grafana/provisioning/dashboards/all.yml
      - ./gateway/monitoring/grafana/krakend:/var/lib/grafana/dashboards/krakend
    environment:
      - GF_LOG_LEVEL=debug

 influxdb:
    image: influxdb:1.8.10
    environment:
      - "INFLUXDB_DB=krakend"
      - "INFLUXDB_USER=krakend-dev"
      - "INFLUXDB_USER_PASSWORD=pas5w0rd"
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=supersecretpassword"
    ports:
      - "8086:8086"