name: Docs as Code

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./documentation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Install Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Install PlantUML
        run: |
          wget -q https://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O plantuml.jar

      - name: Convert PlantUML diagrams to PNG
        run: |
          find . -name "*.puml" -exec java -jar plantuml.jar -tpng {} \;

      - name: List all PNG files
        run: |
          find . -name "*.png" -exec echo {} \;

      - name: Install Asciidoctor
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full
          sudo gem install asciidoctor

      - name: Convert Asciidoctor file to HTML
        run: |
          asciidoctor main.adoc -o main.html

      - name: Move and rename HTML file
        run: |
          mv main.html index.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: documentation-artifacts
          path: |
            ./documentation/index.html
            ./documentation/*.png

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: documentation-artifacts

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
