name: Release gateway

on:
  push:
    branches:
      - main
    # Only run workflow for changes in the gateway service
    paths:
      - "services/gateway/**"
      - ".github/workflows/release-gateway.yml"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build and push gateway
        uses: docker/build-push-action@v5
        with:
          context: ./services/gateway
          push: true
          tags: |
            rensvangiersbergen/wallmarkt-gateway:latest
            rensvangiersbergen/wallmarkt-gateway:${{ github.sha }}
      - name: Build and push Grafana
        uses: docker/build-push-action@v5
        with:
          context: ./services/gateway/monitoring/grafana
          push: true
          tags: |
            rensvangiersbergen/wallmarkt-grafana:latest
            rensvangiersbergen/wallmarkt-grafana:${{ github.sha }}
