name: Release product-service

on:
  push:
    branches:
      - main
    # Only run workflow for changes in the product service
    paths:
      - "services/product/**"
      - ".github/workflows/release-product-service.yml"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build and push product-service
        uses: docker/build-push-action@v5
        with:
          context: ./services/product
          push: true
          tags: |
            rensvangiersbergen/wallmarkt-product-service:latest
            rensvangiersbergen/wallmarkt-product-service:${{ github.sha }}

  build-and-deploy:
    needs: build-and-publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PRODUCTSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PRODUCTSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PRODUCTSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/services/product
          registryUrl: docker.io
          registryUsername: ${{ secrets.PRODUCTSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PRODUCTSERVICE_REGISTRY_PASSWORD }}
          containerAppName: product-service
          resourceGroup: Wallmarkt
          imageToBuild: rensvangiersbergen/product-service:${{ github.sha }}
