name: Release product-service

on:
  push:
    branches:
      - main
    # Only run workflow for changes in the product service
    paths:
      - "services/product/**"
      - ".github/workflows/release-product-service.yml"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build and push product-service
        uses: docker/build-push-action@v5
        with:
          context: ./services/product
          push: true
          tags: |
            rensvangiersbergen/wallmarkt-product-service:latest
            rensvangiersbergen/wallmarkt-product-service:${{ github.sha }}
