name: Release product-service

on:
  push:
    branches:
      - main
    # Only run workflow for changes in the wms frontend
    paths:
      - "web/wms/**"
      - ".github/workflows/release-wms-frontend.yml"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build and push wms-frontend
        uses: docker/build-push-action@v5
        with:
          context: ./web/wms
          push: true
          tags: |
            rensvangiersbergen/wallmarkt-wms-frontend:latest
            rensvangiersbergen/wallmarkt-wms-frontend:${{ github.sha }}
