name: Test & Lint shipping-service

on:
  pull_request:
    # Only run workflow for pull requests to the development branch
    types: [opened, synchronize, reopened]
    branches:
      - development
    # Only run workflow for changes in the order service
    paths:
      - "services/shipping/**"
      - ".github/workflows/test-lint-shipping-service.yml"
  workflow_dispatch:

jobs:
  # Test building the go project
  build:
    name: Building shipping service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - name: Building
        run: |
          cd services/order
          go run cmd/main.go

  # Run linter for readability
  golangci-lint:
    needs: build
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          working-directory: services/shipping
          args: --timeout 5m

  # Test unit tests
  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/shipping
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - name: Run tests
        run: go test ./services/shipping/...
