name: ZAP DAST Scan on KrakenD Gateway

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the application
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Start Application
        run: docker compose up -d

      - name: Wait for Application to Start
        uses: jakejarvis/wait-action@master
        with:
          time: "10s"

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          target: "http://localhost:8080"
          cmd_options: "-a"
